### ISSUE TITLE
ImportError: No module named folium

### ISSUE THREAD

**Issue by crypdick** [crypdick/police-traffic-stop-explorer#11]
```
rdecal@flask01:/var/www/PoliceStops$ python run.py 
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "/var/www/PoliceStops/app/__init__.py", line 4, in <module>
    from app import views
  File "/var/www/PoliceStops/app/views.py", line 4, in <module>
    import viz
  File "/var/www/PoliceStops/viz.py", line 2, in <module>
    import folium
ImportError: No module named folium
```

**Comment by crypdick** [comment]
Nevermind. to my pleasant surprise I had pip install privileges-- installed pandas, folium, numpy, urllib
